version: '3'

services:
  bingo-db:
    image: postgres:12
    container_name: bingo-db
    restart: unless-stopped
    env_file: .env
    volumes: 
      - bingo-dbdata:/var/lib/postresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '6000:5432'
    networks:
      - app-network

  bingo-web:
    depends_on: 
      - bingo-db
    build: .
    container_name: bingo-web
    restart: unless-stopped
    env_file: .env    
    ports:
      - '5000:80'
    networks:
      - app-network

volumes:
  bingo-dbdata:

networks:
  app-network:
    driver: bridge
